imu_zupt:
  ros__parameters:
    topics:
      imu: /imu/data
      output: /imu/data_zupt
      error: /imu/yaw_err
      filter_status: /imu_zupt/active
      input_status: /input_status
    covariance:
      override: true
      value: 0.001
    error:
      publish: true
      in_degrees: true
    zero_velocity_detection:
      seconds: 2.0
      publish: true