imu_zupt:
  ros__parameters:
    topics:
      locomotion: /locomotion/odom
      imu: /imu/data
      output: /imu/data_zupt
      error: /imu/yaw_err
      status: /imu_zupt/active
    covariance:
      override: true
      value: 0.001
    error:
      publish: true
      in_degrees: true
    zero_velocity_detection:
      seconds: 2.0
      publish: true